### ISSUE TITLE
How to get login credentials

### ISSUE THREAD

**Issue by SuhanaShaik671** [edutiv/edutiv-flutter#2]
Provide the login credentials please..

**Comment by geniusvale** [comment]
Previously credentials are available on demo video, but unfortunately now the servers are shutdown and the project is deprecated and no longer used. Still you can fork the repo and modify code to remove login restriction for learning purposes.

**Comment by SuhanaShaik671** [comment]
Iam trying it but iam not get it can u help me in this. Can u remove the
credentials part..
 It's my humble request to u
